### ISSUE TITLE
As an aviation enthusiast, Imad Roshan is passionate about tracking airplanes passing by his house and staying informed about their flight data. 

### ISSUE THREAD

**Issue by imadroshan** [imadroshan/SkySpy#1]
So that he can stay informed about the flight's position, speed, altitude, flight number, departure and arrival airports, scheduled departure and arrival times, and aircraft type. 

A sensor or software-defined-radio should be setup at home and connected to the OpenSky Network, to detect airplanes passing overhead. Sensor detects an airplane flying nearby. The system sends a request to the Opensky Network API to retrieve live data for the detected airplane, including its position, speed, altitude, and more. The live data is then stored in the Redis database for easy retrieval. 
To gather additional flight information, such as flight number, departure and arrival airports, scheduled departure and arrival times, the system scrapes the FlightAware website using the Callsign number. Once the system scrapes the requested information, the system processes and displays the live airplane data and additional flight information on the frontend for users to view.

## Task for this Use-Case:
- [ ] #2
- [ ] #3
- [ ] #4
- [ ] #5
- [ ] #6
- [ ] #7
- [ ] #8
- [ ] #9

**Comment by imadroshan** [comment]
Task for this Use-Case:
- [ ] User sets up a sensor to detect airplanes passing overhead. 
- [ ] The sensor detects an airplane and obtains associated data. 
- [ ] The system sends a request to the Opensky Network API to retrieve live data of the detected airplanes. 
- [ ] Opensky Network API responds with the live data of the airplane, including its position, speed, altitude, etc. 
- [ ] The system stores the received live data in the Redis Database. 
- [ ] The system scrapes the FlightAware website using the Callsign number of the aircraft to retrieve additional flight information, such as flight number, departure and arrival airports, and arrival times.  
- [ ] The scrapper responds with the requested flight information and stores it in the Redis Database.  
- [ ] The system processes and displays the live airplane data and additional flight information on the frontend for the user to view.
